### ISSUE TITLE
Browsermob-proxy release is no longer available

### ISSUE THREAD

**Issue by raresraf** [parasdahal/speedprofile#4]
Unavailable resource: 

`wget https://github.com/downloads/lightbody/browsermob-proxy/browsermob-proxy-2.0-beta-6-bin.zip`

**Comment by parasdahal** [comment]
Please use https://github.com/lightbody/browsermob-proxy/releases/download/browsermob-proxy-2.1.4/browsermob-proxy-2.1.4-bin.zip 

I have also updated README to point to the Github Repo.
